/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.algebra;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import hr.algebra.user.view.EditMoviesPanel;
import hr.algebra.admin.view.UploadMoviesPanel;
import hr.algebra.user.view.EditActorPanel;
import hr.algebra.user.view.EditDirectorPanel;
import javax.swing.UIManager;

/**
 *
 * @author branimir.maric
 */
public class MovieManager extends javax.swing.JFrame {

    private static final String UPLOAD_MOVIES = "Upload movies";
    private static final String EDIT_MOVIES = "Edit movies";
    private static final String EDIT_ACTOR = "Edit actor";
    private static final String EDIT_DIRECTOR = "Edit director";
//    private static final String DRAGNDROP = "Drag and drop";

    /**
     * Creates new form MovieManager
     */
    public MovieManager() {
        initComponents();
        configurePanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpContent = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MovieManager().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    private void configurePanels() {
        tpContent.add(UPLOAD_MOVIES, new UploadMoviesPanel()); // ADMIN
        tpContent.add(EDIT_MOVIES, new EditMoviesPanel()); // USER
        tpContent.add(EDIT_ACTOR, new EditActorPanel()); // USER
        tpContent.add(EDIT_DIRECTOR, new EditDirectorPanel()); // USER        
//        tpContent.add(DRAGNDROP, new ActorNDirector()); // USER        
    }
}
